--- # Ansible Role [Common]: tasks.main (Axel Pardemann <axelitus@GitHub>)
- name: Include OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- include: "{{ ansible_distribution }}/add_repos.yml"
- include: "{{ ansible_distribution }}/install_tools.yml"