--- # Ansible Role [Common]: tasks.ubuntu.add_repos (Axel Pardemann <axelitus@GitHub>)
- name: Add PPA Repositories
  apt_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state }}"
  with_items: "{{ axelitus_common_repos }}"
  register: common_add_repos